#!/usr/bin/env python3
"""
Script to create the journal_entries table in Supabase
"""
from database import get_supabase_client

def create_journal_entries_table():
    """Create the journal_entries table in Supabase"""
    
    # SQL to create the journal_entries table
    create_table_sql = """
    CREATE TABLE IF NOT EXISTS journal_entries (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id TEXT NOT NULL,
        psalm_id INT8 NOT NULL,
        prompt_responses JSONB NOT NULL,
        created_at TIMESTAMPTZ DEFAULT NOW()
    );
    
    -- Create index on user_id for better query performance
    CREATE INDEX IF NOT EXISTS idx_journal_entries_user_id ON journal_entries(user_id);
    
    -- Create index on psalm_id for better query performance
    CREATE INDEX IF NOT EXISTS idx_journal_entries_psalm_id ON journal_entries(psalm_id);
    
    -- Create composite index for user + psalm queries
    CREATE INDEX IF NOT EXISTS idx_journal_entries_user_psalm ON journal_entries(user_id, psalm_id);
    """
    
    try:
        supabase = get_supabase_client()
        
        # Execute the SQL using Supabase's RPC feature
        # Note: This requires a stored procedure in Supabase, or we use raw SQL
        
        print("Creating journal_entries table...")
        print("SQL to execute:")
        print(create_table_sql)
        
        # For now, just print the SQL - the user will need to run this in Supabase SQL editor
        print("\nTo create the table:")
        print("1. Go to your Supabase dashboard")
        print("2. Navigate to SQL Editor")
        print("3. Run the above SQL")
        print("4. Enable Row Level Security if desired")
        
        return True
        
    except Exception as e:
        print(f"Error: {e}")
        return False

if __name__ == "__main__":
    create_journal_entries_table()